# .github/workflows/deploy-assets.yml
name: Deploy Assets to wizice/wzprod_nfctemp

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'app/src/main/assets/**'
      - '.github/workflows/deploy-assets.yml'
      - 'scripts/**'
  workflow_dispatch: # 수동 실행 가능

env:
  PUBLIC_REPO: wizice/wzprod_nfctemp

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout private repository
      uses: actions/checkout@v3
      with:
        path: private-repo
    
    - name: Checkout public repository (wizice/wzprod_nfctemp)
      uses: actions/checkout@v3
      with:
        repository: ${{ env.PUBLIC_REPO }}
        token: ${{ secrets.PUBLIC_REPO_TOKEN }}
        path: public-repo
        fetch-depth: 0  # 전체 히스토리 가져오기
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: private-repo/package-lock.json
    
    - name: Install dependencies
      run: |
        cd private-repo
        npm ci
    
    - name: Run pre-deployment checks
      run: |
        cd private-repo
        npm run check || echo "Pre-deployment checks completed with warnings"
    
    - name: Determine target branch
      id: branch
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "target=main" >> $GITHUB_OUTPUT
          echo "env=prod" >> $GITHUB_OUTPUT
        else
          echo "target=develop" >> $GITHUB_OUTPUT
          echo "env=dev" >> $GITHUB_OUTPUT
        fi
    
    - name: Switch to target branch in public repo
      run: |
        cd public-repo
        git fetch origin
        
        # 브랜치가 존재하는지 확인
        if git show-ref --quiet refs/remotes/origin/${{ steps.branch.outputs.target }}; then
          git checkout ${{ steps.branch.outputs.target }}
          git pull origin ${{ steps.branch.outputs.target }}
        else
          git checkout -b ${{ steps.branch.outputs.target }}
        fi
    
    - name: Clean old assets
      run: |
        cd public-repo
        # version.json과 .git 폴더를 제외하고 모두 삭제
        find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'version.json' ! -name '.github' -exec rm -rf {} +
    
    - name: Copy assets
      run: |
        cd private-repo
        
        # assets 폴더의 내용물 복사
        if [ -d "app/src/main/assets" ]; then
          cp -r app/src/main/assets/* ../public-repo/
          echo "✅ Assets copied successfully"
        else
          echo "❌ Assets directory not found!"
          exit 1
        fi
    
    - name: Calculate checksums
      id: checksums
      run: |
        cd private-repo
        node scripts/calculate-checksums.js
        
        # 체크섬 파일을 public repo에도 복사 (선택사항)
        cp checksums.json ../public-repo/checksums.json
    
    - name: Create version info
      run: |
        cd public-repo
        
        # 버전 정보 생성
        cat > version.json << EOF
        {
          "version": "${{ github.run_number }}-${{ github.sha }}",
          "build_number": "${{ github.run_number }}",
          "branch": "${{ steps.branch.outputs.target }}",
          "commit": "${{ github.sha }}",
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "environment": "${{ steps.branch.outputs.env }}",
          "deployed_by": "${{ github.actor }}",
          "github_pages_url": "https://wizice.github.io/wzprod_nfctemp"
        }
        EOF
        
        echo "📄 Version info created"
    
    - name: Create index.html for GitHub Pages
      run: |
        cd public-repo
        
        # GitHub Pages용 index.html 생성
        cat > index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="ko">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>WizIce NFC Temp Assets</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
                       margin: 40px; background: #f5f5f5; }
                .container { max-width: 800px; margin: 0 auto; background: white; 
                           padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                h1 { color: #333; }
                .info { background: #e3f2fd; padding: 15px; border-radius: 5px; margin: 20px 0; }
                .version { font-family: monospace; background: #f5f5f5; padding: 10px; 
                          border-radius: 3px; }
                a { color: #1976d2; text-decoration: none; }
                a:hover { text-decoration: underline; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🌡️ WizIce NFC Temperature Assets</h1>
                <div class="info">
                    <p>This repository contains public assets for the WizIce NFC Temperature application.</p>
                    <p><strong>Environment:</strong> <span class="version">${{ steps.branch.outputs.env }}</span></p>
                    <p><strong>Branch:</strong> <span class="version">${{ steps.branch.outputs.target }}</span></p>
                    <p><strong>Last Updated:</strong> <span class="version">$(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)</span></p>
                </div>
                
                <h2>📁 Available Resources</h2>
                <ul>
                    <li><a href="version.json">version.json</a> - Version information</li>
                    <li><a href="checksums.json">checksums.json</a> - File checksums</li>
                </ul>
                
                <h2>🔗 Quick Links</h2>
                <ul>
                    <li><a href="https://github.com/wizice/wzprod_nfctemp">GitHub Repository</a></li>
                    <li><a href="https://raw.githubusercontent.com/wizice/wzprod_nfctemp/${{ steps.branch.outputs.target }}/version.json">
                        Raw Version Info</a></li>
                </ul>
                
                <hr style="margin-top: 40px; border: none; border-top: 1px solid #eee;">
                <p style="text-align: center; color: #666; font-size: 14px;">
                    Deployed by GitHub Actions • Build #${{ github.run_number }}
                </p>
            </div>
        </body>
        </html>
        EOF
    
    - name: Commit and push changes
      run: |
        cd public-repo
        
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        git add .
        
        # 변경사항 확인
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # 커밋 메시지 생성
        COMMIT_MSG="Deploy assets from ${{ github.ref_name }} - Build #${{ github.run_number }}"
        COMMIT_DESC="Source: ${{ github.repository }}@${{ github.sha }}"
        
        git commit -m "$COMMIT_MSG" -m "$COMMIT_DESC"
        git push origin ${{ steps.branch.outputs.target }}
        
        echo "✅ Successfully pushed to wizice/wzprod_nfctemp"
    
    - name: Update Firestore (if service account exists)
      if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        cd private-repo
        
        # Firebase 서비스 계정 생성
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
        
        # Firestore 업데이트
        node scripts/update-firestore-version.js \
          --env ${{ steps.branch.outputs.env }} \
          --version "${{ github.run_number }}-${{ github.sha }}" \
          --repo "${{ env.PUBLIC_REPO }}" || echo "Firestore update skipped"
        
        # 서비스 계정 파일 삭제
        rm -f firebase-service-account.json
    
    - name: Summary
      run: |
        echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Repository**: wizice/wzprod_nfctemp" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ steps.branch.outputs.target }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ steps.branch.outputs.env }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build**: #${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔗 URLs" >> $GITHUB_STEP_SUMMARY
        echo "- [GitHub Pages](https://wizice.github.io/wzprod_nfctemp/)" >> $GITHUB_STEP_SUMMARY
        echo "- [Raw Files](https://raw.githubusercontent.com/wizice/wznfctemp/${{ steps.branch.outputs.target }}/)" >> $GITHUB_STEP_SUMMARY
